### ISSUE TITLE
Add GUI support

### ISSUE THREAD

**Issue by Jothin-kumar** [Harsha200105/DesktopAssistant#16]
It would really great if this assistant has a GUI. I am working on it and will create a pull request soon!

**Comment by Harsha200105** [comment]
@Jothin-kumar : Well, I'm glad you thought of it btw I'm working on the GUI as well. Never thought someone will raise an issue regarding that!! Go ahead. If you need any help just let me know.

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar : Well, I'm glad you thought of it btw I'm working on the GUI as well. Never thought someone will raise an issue regarding that!! Go ahead. If you need any help just let me know.

I have now started a pull request, check it out!
Now, this GUI is simple. I can add more features to the GUI if you want any.
Thank you
