### ISSUE TITLE
Create requirement.txt file for running the desktop assistant program

### ISSUE THREAD

**Issue by Harsha200105** [Harsha200105/DesktopAssistant#3]
Create a requirements.txt file for the desktop assistant program

**Comment by gunjan1622** [comment]
I would like to work on this issue.

**Comment by Harsha200105** [comment]
@gunjan1622 : Sure! Go ahead!!! If you face any specific issues get back to me.

**Comment by PANDATD** [comment]
-  We can add dependancy bot which is available on GitHub I think I'm able to work  on it

**Comment by NaveenKumarReddy8** [comment]
Hey Guys,
It would be great if you could use [Poetry](https://python-poetry.org/)  for dependency management, this is a great tool. I use this for my personal projects.

**Comment by Harsha200105** [comment]
Great Ideas @PANDATD and @NaveenKumarReddy8 : I had tried dependabot but didn't have great experience with it would like to go with ![poetry](https://python-poetry.org/).

**Comment by Harsha200105** [comment]
@PANDATD : Would you like to add [poetry](https://python-poetry.org/) to the repo

**Comment by Harsha200105** [comment]
@PANDATD : Great then go ahead!!! If any specific issues let me know!!

**Comment by PANDATD** [comment]
> @PANDATD : Great then go ahead!!! If any specific issues let me know!!

Yup 😀 why not dude

**Comment by PANDATD** [comment]
> @PANDATD : Would you like to add [poetry](https://python-poetry.org/) to the repo

Yes but give me some time to to do it 😜 dude

**Comment by cclauss** [comment]
On Linux, you will need to run #35

**Comment by dzek69** [comment]
And what on windows? Because it crashes with the same thing on windows. Error messages are a bit different, but about the same file missing anyway

**Comment by cclauss** [comment]
macOS is complicated especially on an M1 Mac but I got it to work.

Life is too short to use Windows.

**Comment by HemanthSai7** [comment]
@Harsha200105 Can I work on this issue?
