### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by Zenahr** [Harsha200105/DesktopAssistant#44]
Having a pre-built binary version would be really useful for new users to test things out first.

**Comment by Jothin-kumar** [comment]
> @Zenahr : Even I am willing to create an executable Desktop Assistant. Are you willing to take this up!!!

@Harsha200105 I can take up deb packages and EXE files if you want.

**Comment by Jothin-kumar** [comment]
@Harsha200105, @Zenahr Done! I have opened a PR #59 for this.
