### ISSUE TITLE
There is a problem with the GUI.

### ISSUE THREAD

**Issue by Dasemu** [Harsha200105/DesktopAssistant#52]
There is a problem with the GUI. At least on my PC the GUI window is bigger than it should be, I mean, my screen is 1920 x 1080, the GUI window must be more or less 200 x 3000 so I can't use the GUI as the chat box is not being shown in my screen. I have a PC with Windows 10 and 2 screens.

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar 

Thank you for reporting the bug, I would fix it asap
